import { createServer, type Server, type ServerResponse } from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";

import type {
  BojUserSubmissionRow,
  BojUserSubmissionsSnapshot,
} from "../boj/session.js";
import { ConfigurationError } from "../errors.js";
import {
  type ReactRenderSubmissionsStatusOptions,
  renderSubmissionsNotFoundReactPage,
  renderSubmissionsStatusReactPage,
} from "./react/submissions-page.js";
import { BOJ_FAVICON_32_URL } from "./react/render.js";

const ROW_INDEX = {
  submissionId: 0,
  problemId: 1,
  problemTitle: 2,
  result: 3,
  resultClass: 4,
  memoryKb: 5,
  timeMs: 6,
  language: 7,
  codeLength: 8,
  submittedAt: 9,
  submittedAtTimestamp: 10,
} as const;

export interface StartSubmissionsViewerOptions {
  inputPath: string;
  host: string;
  port: number;
}

export interface StartedSubmissionsViewer {
  server: Server;
  username: string;
  inputPath: string;
  statusUrl: string;
}

export interface RenderSubmissionsStatusOptions {
  localProfileOrigin?: string | null;
  problemNav?: ReactRenderSubmissionsStatusOptions["problemNav"];
}

export async function startSubmissionsViewerServer(
  options: StartSubmissionsViewerOptions,
): Promise<StartedSubmissionsViewer> {
  const inputPath = path.resolve(options.inputPath);
  const snapshot = await readSubmissionsSnapshot(inputPath);
  const username = snapshot.username;

  const server = createServer((request, response) => {
    const requestUrl = new URL(request.url ?? "/", `http://${request.headers.host ?? "localhost"}`);
    const pathname = decodeURIComponent(requestUrl.pathname);

    if (pathname === "/") {
      response.writeHead(302, {
        Location: `/status?user_id=${encodeURIComponent(username)}`,
      });
      response.end();
      return;
    }

    if (pathname === "/favicon.ico") {
      response.writeHead(302, { Location: BOJ_FAVICON_32_URL });
      response.end();
      return;
    }

    if (pathname === "/status") {
      const requestedUser = requestUrl.searchParams.get("user_id");

      if (!requestedUser || requestedUser === username) {
        respondHtml(response, renderSubmissionsStatusPage(snapshot, requestUrl.origin));
        return;
      }
    }

    response.writeHead(404, { "content-type": "text/html; charset=utf-8" });
    response.end(renderNotFoundPage(username, requestUrl.origin));
  });

  await new Promise<void>((resolve, reject) => {
    const onError = (error: unknown) => {
      reject(normalizeServerStartError(error, options.host, options.port));
    };

    server.once("error", onError);
    server.listen(options.port, options.host, () => {
      server.off("error", onError);
      resolve();
    });
  });

  const address = server.address();
  if (!address || typeof address === "string") {
    throw new Error("Could not determine submissions viewer server address.");
  }

  const displayHost = options.host === "0.0.0.0" ? "127.0.0.1" : options.host;
  const baseUrl = `http://${displayHost}:${address.port}`;

  return {
    server,
    username,
    inputPath,
    statusUrl: `${baseUrl}/status?user_id=${encodeURIComponent(username)}`,
  };
}

export function renderSubmissionsStatusPage(
  snapshot: BojUserSubmissionsSnapshot,
  origin: string,
  options: RenderSubmissionsStatusOptions = {},
): string {
  return renderSubmissionsStatusReactPage(snapshot, origin, options);
}

async function readSubmissionsSnapshot(inputPath: string): Promise<BojUserSubmissionsSnapshot> {
  let raw: string;

  try {
    raw = await readFile(inputPath, "utf8");
  } catch {
    throw new ConfigurationError(`Could not read submissions JSON: ${inputPath}`);
  }

  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new ConfigurationError(`Submissions JSON is not valid JSON: ${inputPath}`);
  }

  if (!isSubmissionsSnapshot(parsed)) {
    throw new ConfigurationError(
      "Submissions JSON must contain username, columns, and rows generated by the submissions command.",
    );
  }

  return parsed;
}

function isSubmissionsSnapshot(value: unknown): value is BojUserSubmissionsSnapshot {
  if (!value || typeof value !== "object") {
    return false;
  }

  const snapshot = value as Partial<BojUserSubmissionsSnapshot>;
  return (
    typeof snapshot.username === "string" &&
    Array.isArray(snapshot.columns) &&
    Array.isArray(snapshot.rows)
  );
}

function renderStatusTable(
  snapshot: BojUserSubmissionsSnapshot,
  options: RenderSubmissionsStatusOptions,
): string {
  const visibleColumns = snapshot.columns.filter((column) => column.visible);
  const headers = visibleColumns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("");
  const rows = snapshot.rows.map((row) => renderStatusRow(snapshot.username, row, options)).join("");

  return `<table class="table table-striped table-bordered" id="status-table"><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
}

function renderStatusRow(
  username: string,
  row: BojUserSubmissionRow,
  options: RenderSubmissionsStatusOptions,
): string {
  const submissionId = row[ROW_INDEX.submissionId];
  const problemId = row[ROW_INDEX.problemId];
  const problemTitle = row[ROW_INDEX.problemTitle];
  const result = row[ROW_INDEX.result];
  const resultClass = row[ROW_INDEX.resultClass];
  const memoryKb = row[ROW_INDEX.memoryKb];
  const timeMs = row[ROW_INDEX.timeMs];
  const language = row[ROW_INDEX.language];
  const codeLength = row[ROW_INDEX.codeLength];
  const submittedAt = row[ROW_INDEX.submittedAt];

  const problemCell =
    problemId !== null
      ? `<a href="https://www.acmicpc.net/problem/${problemId}" rel="tooltip" data-placement="right" title="${escapeHtml(problemTitle ?? "")}" class="problem_title tooltip-click" target="_blank">${problemId}</a>`
      : "-";
  const resultCell = resultClass
    ? `<span class="result-text ${escapeHtml(resultClass)}">${escapeHtml(result)}</span>`
    : escapeHtml(result);
  const profileUrl = options.localProfileOrigin
    ? `${options.localProfileOrigin}/user/${encodeURIComponent(username)}`
    : `https://www.acmicpc.net/user/${encodeURIComponent(username)}`;
  const profileAttrs = options.localProfileOrigin ? "" : ' target="_blank" rel="noreferrer"';

  return `
    <tr id="solution-${submissionId}">
      <td class="viewer-submission-id">${submissionId}</td>
      <td><a href="${escapeHtml(profileUrl)}"${profileAttrs}><span class="user-blue">${escapeHtml(username)}</span></a></td>
      <td>${problemCell}</td>
      <td class="result">${resultCell}</td>
      <td class="memory">${escapeHtml(formatValueWithUnit(memoryKb, "KB"))}</td>
      <td class="time">${escapeHtml(formatValueWithUnit(timeMs, "ms"))}</td>
      <td>${escapeHtml(language)}</td>
      <td>${escapeHtml(formatValueWithUnit(codeLength, "B"))}</td>
      <td><a href="https://www.acmicpc.net/status?user_id=${encodeURIComponent(username)}" target="_blank" rel="noreferrer">${escapeHtml(submittedAt ?? "-")}</a></td>
    </tr>
  `;
}

function renderShell(args: {
  title: string;
  activeNav: "status";
  username: string;
  origin: string;
  options: RenderSubmissionsStatusOptions;
  content: string;
}): string {
  return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(args.title)}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://ddo7jzca0m2vt.cloudfront.net/unify/css/style.css?version=20240112">
  <link rel="stylesheet" href="https://ddo7jzca0m2vt.cloudfront.net/css/connect.css?version=20240112">
  <link rel="stylesheet" href="https://ddo7jzca0m2vt.cloudfront.net/css/result.css?version=20240112">
  <link rel="stylesheet" href="https://ddo7jzca0m2vt.cloudfront.net/css/label.css?version=20240112">
  <link rel="stylesheet" href="https://ddo7jzca0m2vt.cloudfront.net/unify/css/custom.css?version=20240112">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://ddo7jzca0m2vt.cloudfront.net/unify/css/theme-colors/blue.css?version=20240112">
  <link rel="stylesheet" href="https://ddo7jzca0m2vt.cloudfront.net/css/fa-color.css?version=20240112">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,700|Open+Sans:400,400i,700,700i|Source+Code+Pro&amp;subset=korean" rel="stylesheet">
  <style>
    body { background: #fff; color: #333; }
    a, a:focus, a:hover, a:active { color: #0076c0; }
    .viewer-topbar-note { margin-left: 10px; color: #777; font-size: 12px; }
    .viewer-nav .navbar-nav > li > a { padding-left: 14px; padding-right: 14px; }
    .viewer-status-meta {
      margin-bottom: 12px;
      color: #555;
      font-size: 12px;
    }
    .viewer-status-links {
      margin-top: 10px;
      font-size: 12px;
    }
    .viewer-status-wrap {
      max-height: 75vh;
      overflow: auto;
      border: 1px solid #ddd;
      border-radius: 4px;
    }
    .viewer-status-wrap table {
      margin-bottom: 0;
    }
    .viewer-status-wrap thead th {
      position: sticky;
      top: 0;
      background: #fff;
      z-index: 1;
    }
    .viewer-submission-id {
      font-family: "Source Code Pro", monospace;
      white-space: nowrap;
    }
    @media (max-width: 767px) {
      .viewer-topbar-note { display: none; }
    }
  </style>
</head>
<body>
  <div class="wrapper">
    ${renderTopChrome(args.origin, args.activeNav, args.username, args.options)}
    <div class="container content">
      ${args.content}
    </div>
  </div>
</body>
</html>`;
}

function renderTopChrome(
  origin: string,
  activeNav: "status",
  username: string,
  options: RenderSubmissionsStatusOptions,
): string {
  const profileUrl = options.localProfileOrigin
    ? `${options.localProfileOrigin}/user/${encodeURIComponent(username)}`
    : "https://www.acmicpc.net/ranklist";
  return `
    <div class="header no-print">
      <div class="topbar">
        <div class="container">
          <ul class="loginbar pull-right">
            <li><a href="https://www.acmicpc.net/register" target="_blank" rel="noreferrer">회원가입</a></li>
            <li class="topbar-devider"></li>
            <li><a href="https://www.acmicpc.net/login" target="_blank" rel="noreferrer">로그인</a></li>
          </ul>
        </div>
      </div>
      <div class="navbar navbar-default mega-menu viewer-nav" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="${escapeHtml(options.localProfileOrigin ? profileUrl : `${origin}/status`)}">
              <img id="logo-header" src="https://d2gd6pc034wcta.cloudfront.net/images/logo@2x.png" alt="Logo" data-retina>
            </a>
          </div>
          <div class="collapse navbar-collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><a href="https://www.acmicpc.net/problemset" target="_blank" rel="noreferrer">문제</a></li>
              <li><a href="https://www.acmicpc.net/workbook/top" target="_blank" rel="noreferrer">문제집</a></li>
              <li><a href="https://www.acmicpc.net/contest/official/list" target="_blank" rel="noreferrer">대회</a></li>
              <li class="active"><a href="${escapeHtml(`${origin}/status`)}">채점 현황</a></li>
              <li><a href="${escapeHtml(profileUrl)}"${options.localProfileOrigin ? "" : ' target="_blank" rel="noreferrer"'}>랭킹</a></li>
              <li><a href="https://www.acmicpc.net/board/list/all" target="_blank" rel="noreferrer">게시판</a></li>
              <li><a href="https://www.acmicpc.net/group/list/all" target="_blank" rel="noreferrer">그룹</a></li>
            </ul>
            <span class="navbar-text viewer-topbar-note">local submissions viewer</span>
          </div>
        </div>
      </div>
    </div>
  `;
}

function renderNotFoundPage(username: string, origin: string): string {
  return renderSubmissionsNotFoundReactPage(username, origin);
}

function respondHtml(response: ServerResponse, html: string): void {
  response.writeHead(200, { "content-type": "text/html; charset=utf-8" });
  response.end(html);
}

function formatValueWithUnit(value: number | null, unit: string): string {
  if (value === null) {
    return "-";
  }

  return `${formatNumber(value)}${unit}`;
}

function formatDateTime(value: string): string {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("ko-KR", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat("ko-KR").format(value);
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function normalizeServerStartError(error: unknown, host: string, port: number): Error {
  if (error && typeof error === "object" && "code" in error) {
    const code = String((error as { code?: unknown }).code);

    if (code === "EADDRINUSE") {
      return new ConfigurationError(`Port ${port} is already in use.`);
    }

    if (code === "EACCES") {
      return new ConfigurationError(
        `Could not bind to ${host}:${port}. That port may be restricted by Windows. Try --port 3000 or --port 0.`,
      );
    }
  }

  return error instanceof Error ? error : new Error(String(error));
}
